# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_O0YJEA-UGJz4oHknOaMIxZP3PwzYkN
"""

!pip install prettytable

from prettytable import PrettyTable

receipt= PrettyTable()
receipt.field_names = ['№','продукт','цена','количество','стоимость']

print(receipt)